name: Pull request

on:
  push:
    branches: ["master"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    -name: unitTests
     run: ./gradlew testDebugUnit
     
   

    
    

  
